title: "silvuss's thoughts"
description: "hello, i am silvuss, and here you can find my thoughts on programming, and maybe some other topics. english is not my native language."
copyright-note: "all articles (thoughts) in this place has no license. for more information, see [this page from github](https://choosealicense.com/no-permission/)."
url: https://silvuss.github.io/